src/libplctag/LibraryExtractor.cs

After doing some more research, the library embed/extract actually does seem to be the way things like SQLite and others do it when they are used on a wide variety of platforms.
https://ericsink.com/entries/native_library.html

Seems to work with Core and Framework

---

src/libplctag/Generic/GenericTag.cs
src/libplctag/ITag.cs
src/libplctag/LibPlcTag.cs
src/libplctag/Tag.cs

Hi @jkoplo - it would be good to get your opinion on this.
Given that debug level is global and isn't per tag, I thought it could make sense to move it to the library utility class and remove it from the tag constructor. We were talking about taking steps to reduce the size of the constructor.
So you just use it by setting it on the static utility class:
```csharp
LibPlcTag.DebugLevel = DebugLevel.Warn;
var tag = new Tag(...)
```

Move Debug level to global utility class

---

src/Examples/CSharp DotNetCore/CSharp DotNetCore.csproj
src/Examples/CSharp DotNetCore/ExampleArray.cs
src/Examples/CSharp DotNetCore/ExampleAsync.cs
src/Examples/CSharp DotNetCore/ExampleGenericTag.cs
src/Examples/CSharp DotNetCore/ExampleListTags.cs
src/Examples/CSharp DotNetCore/Program.cs
src/Examples/CSharp DotNetCore/SequenceMarshaller.cs
src/Examples/CSharp DotNetCore/TestDatatypes.cs
src/libplctag/DataTypes/BoolMarshaller.cs
src/libplctag/DataTypes/DintMarshaller.cs
src/libplctag/DataTypes/IMarshaller.cs
src/libplctag/DataTypes/IntMarshaller.cs
src/libplctag/DataTypes/LintMarshaller.cs
src/libplctag/DataTypes/LrealMarshaller.cs
src/libplctag/DataTypes/Marshaller.cs
src/libplctag/DataTypes/RealMarshaller.cs
src/libplctag/DataTypes/SintMarshaller.cs
src/libplctag/DataTypes/StringMarshaller.cs
src/libplctag/DataTypes/TagInfoMarshaller.cs
src/libplctag/DataTypes/TimerMarshaller.cs
src/libplctag/TagOfT.cs

I took a bit of a wrong turn at first, but I ended up putting together something that I'm really happy with regarding how we're handling the conversion code. I moved back to interfaces, but kept the base class in order to duplicate as little code as possible between the marshallers/mappers.
I feel a bit uneasy about the marshaller forcing both a single and an array implementation for a given type, but we can always choose to not use the marshaller and implement directly against the interface.
Good classes to review to go check out the implemenation:
- Simple dataype (DINT, etc)
- Timer -> Uses the marshaller base class but on a non-simple type
- Bool -> Implements against the interface because Bool isn't clean with offsets
- TagInfo -> Requires interesting custom parsing
- Sequence -> UDT …

Generic typed arrays#2

---

src/libplctag/Tag.cs

@timyhac - What do you think about this?
On the one hand, we're being a little 'too automatic' - users will see a delay on first Read/Write instead of consistent performance.
On the other hand, it's simpler to use, less user code, and I doubt the performance will matter for most use cases. If performance is a concern, people can optimize by calling initialize first.
Thoughts?

If not initialized, call appropriate Init method

---

src/Examples/CSharp DotNetCore/TestDatatypes.cs
src/libplctag/DataTypes/StringPlcMapper.cs
src/libplctag/libplctag.csproj

There was what looked like a copy-paste error that meant CompactLogix strings had two offsets (+ 4 + 2) in use for retrieving the first character.

Bugfix compactlogix strings

---

src/libplctag/DataTypes/BoolPlcMapper.cs
src/libplctag/NativeTagWrapper.cs
src/libplctag/PlcType.cs

This PR adds support for Omron PLCs to the .NET wrapper.
Basically I had to add the `Omron` option to the `PlcType` enumeration.
As in the C library all nemonics for Omron PLC include dashes, which are not allowed in C# enums, I had to create a special case handling on file `NativeTagWrapper.cs`.
Also, booleans are represented differently on the wire than AB PLCs, and I had to take this into account on the `BoolPlcMapper.cs`.
After these changes, I have confirmed with actual Omron hardware (NX1P2) that reading and writing Global Published PLC tags of the following types is possible:
- 16 bits signed integer
- 32 bits signed integer
- 64 bits signed integer
- Boolean
- 32 bits floating point numbers
- 64 bits floating point numbers
My intention in the future is to test arrays and strings. …

Add support for Omron PLC

---

README.md
src/Examples/CSharp DotNetCore/ExampleDatatypesSimple.cs
src/libplctag/DataTypes/Simple/Definitions.cs

Closes #155 
I felt a little dirty writing this code, but the intended end user is for devs that are new-er to C#. Generics can be confusing and even more so when a class is defined with two generics. This is really just some helper syntax to keep things simpler. I put these definitions in a single file in their own `libplctag.Datatypes.Simple` - I figured this should help keep them out of the way of more experienced developers.
I'm open to using different naming conventions for the namespace and for the classes - these were just the first that came to mind. Also, if we do want to merge this, I'll update our main page README to highlight the new simple classes.

Implementing really simple Tag classes

---

src/Examples/CSharp NativeImport/CallbackEx.cs
src/libplctag/NativeTagWrapper.cs

This Pull Request fixes inappropriate disposal (for tags that failed to initialize using InitializeAsync).
When InitializeAsync ReadAsync or WriteAsync times out, it also will ensure that it will fail with a ErrorTimeout as opposed to a ErrorAborted

#246 Fix for inappropriate disposal

---

src/libplctag/NativeTagWrapper.cs
src/libplctag/Tag.cs

Expose SetBuffer function in NativeTagWrapper and Tag, allowing more powerful PLC Mappers

---

src/libplctag/TagOfT.cs

When accessing `PlcType` from inside a PlcMapper always has the default value, as it is not being written anywhere.
This pull request solves this bug.

Pass PlcType to the _plcMapper

---

src/libplctag/Tag.cs
src/libplctag/TagOfT.cs

This provides a reference the outer-most object on events rather than NativeTagWrapper (which is an internal class and shouldn't be exposed).

Refactor events to expose the `this` reference correctly

---

src/libplctag/NativeTagWrapper.cs
src/libplctag/Tag.cs

Fulfills #299 by providing an overload for GetBuffer that accepts a byte array.

Exposes GetBuffer(byte[] buffer)

---

CONTRIBUTIONS.md
README.md
src/Examples/CSharp DotNetCore/ExampleSimulator.cs

* Contains a contributions Policy
* Includes an example of a PLC Fake, referred to in the debugging guidance.

#288 Add Contributions Policy

---

src/libplctag/DataTypes/BoolPlcMapper.cs

Always returns False.
Issue : https://github.com/libplctag/libplctag.NET/issues/178

Issue 178 : Boolean readings do not work with C#

---

src/libplctag/NativeTagWrapper.cs

Currently, as discovered in #327, when using ReadAsync or WriteAsync without first making a call to InitializeAsync and the initialization fails - the exception thrown is of type TaskCancelledException - not LibplctagException.
If I recall correctly, the intention was to throw a  LibplctagException for the libplctag.NET async timeouts, and only to throw a TaskCancelledException if the supplied token is cancelled,
One issue with the attached patch is that there is now two separate timeouts - one for the Initialization, and a second one for the Read - so if there is a 10 second timeout, and a 9 second latency on operations - it will successfully complete in 2*9seconds=18seconds -> maybe the library consumer is expected it to timeout because 18 seconds is larger than the configured timeout. …

Move calls to Initialize above Timeout token

---

src/libplctag/NativeTagWrapper.cs
src/libplctag/TagOfT.cs

Changed all awaits to not run continuations on captured context to prevent deadlocks that occur when a tag is read or written from a UI context.

ConfigureAwait(false) Changes

---

src/libplctag/NativeTagWrapper.cs

The logic should have been if NOT initialized, then get field, otherwise GetDebugLevel - but there is no need to resort to getting debug level because the local field value is always correct.

Fix logic error when getting DebugLevel

---

src/Examples/CSharp DotNetCore/ExampleNotifyChanged.cs

Adding a call to the Initialize() method that is missing.

Call to Initialize() method on ExampleNotifyChanged

---

src/libplctag/NativeTagWrapper.cs

In a case where the length of a string tag is larger than the actual data it contains, an ArgumentOutOfRangeException is thrown. 
To handle this case, I made a small modification to retrieve the data.
I encountered a 'string12' tag that actually contains a string of length 10. When I asked a PLC programmer about this, he told me they're just following the MES. According to him, if it turns out to be their fault or the MES's, it makes sense for us to apply a defensive patch.

Handle string tag length mismatch and retrieve data

---

src/libplctag/NativeTagWrapper.cs
src/libplctag/Tag.cs

After some comments on #359 it became clear that there was a bug in libplctag.NET wrapper code.
Previously it was enforcing the result of set_size to be 0, but the core API says that it is only an error on a negative result and a positive result indicates the previous size.

No throw on positive return value from ..._set_size(...)

---

.github/workflows/build-publish.yml
.github/workflows/update_libplctag_core.yaml
src/Examples/CSharp DotNetCore/CSharp DotNetCore.csproj
src/Examples/CSharp NativeImport/CSharp NativeImport.csproj
src/Examples/VB.NET DotNetCore/VB.NET DotNetCore.vbproj
src/LibplctagReadBenchmark/LibplctagReadBenchmark.csproj
src/libplctag.NativeImport.Benchmarks/libplctag.NativeImport.Benchmarks.csproj
src/libplctag.NativeImport.Tests/libplctag.NativeImport.Tests.csproj
src/libplctag.Tests/libplctag.Tests.csproj

Github actions need to use node v20
Solution projects should use .NET8.0 instead of netcore3.1 or .NET6.0

Update projects to use current versions of node and .NET

---

.github/workflows/build-publish.yml
.github/workflows/update_libplctag_core.yaml
src/Examples/CSharp DotNetCore/CSharp DotNetCore.csproj
src/Examples/CSharp NativeImport/CSharp NativeImport.csproj
src/Examples/VB.NET DotNetCore/VB.NET DotNetCore.vbproj
src/LibplctagReadBenchmark/LibplctagReadBenchmark.csproj
src/libplctag.NativeImport.Benchmarks/libplctag.NativeImport.Benchmarks.csproj
src/libplctag.NativeImport.Tests/libplctag.NativeImport.Tests.csproj
src/libplctag.Tests/libplctag.Tests.csproj
src/libplctag.sln

* Update Github Actions to latest version to support current node (v20 instead of v16)
* Update .NET projects from .NET6 or .NETCore3.1 to .NET8
* Removed Active Build Configurations for build project as per NUKE warnings

Fixes for various Build Warnings

---

src/libplctag.NativeImport/libplctag.NativeImport.csproj

This is a relic from the pre v1.0.0 days, where the IP Address type was (incorrectly) used to force a strong type onto Gateway.

Remove dependency on System.Net.Primitives

---

examples/CSharp DotNetCore/PlcMapper/ExampleListPlc.cs
examples/CSharp DotNetCore/PlcMapper/ExampleMappers.cs
examples/CSharp DotNetCore/PlcMapper/TagOfT.cs

This is a breaking change since it requires IPlcMapper implementations to implement a new method.
As such it will need to go into a 2.x release

Allow Mapper to Configure Tag prior to initialization

---

src/libplctag/LibPlcTag.cs

Ran into this bug when a logging event was added to `LibPlcTag.LogEvent` more than once. This led to an error from `plc_tag_register_logger` being called more than once. Seems like the `alreadySubscribedToEvents` flag wasn't being set true after the first subscription.

Fix repeated log event subscription bug

---

src/libplctag/DataTypes/Extensions/ArrayExtensions.cs

How I discovered it: When I wrote a 3D array into the PLC, I found that the written data was always missing the last number of the third index. Finally, I found that there was a problem when converting the 3D array to a 1D array during encoding.

fix bug: Error in converting 3D array to 1D array (ArrayExtensions.To1DArray)

---

src/libplctag/Tag.cs

I was able to reproduce the memory leak with a simple program with the following structure:
```
var tag = new .... ...;
while(true)
{
await tag.ReadAsync();
await Task.Delay(...);
}
```
If the PLC is online and the tag is readable, there is no memory leak. If there are exceptions on `ReadAsync()` the process slowly increase CPU and memory usage (it may need to keep failing overnight to reach 100% CPU usage in my environment).
**I think the handle created by `plc_tag_create_ex` should be destroyed in `InitializeAsync` regardless of the outcome of the async initialization**. In the current code, if the result of the initialization is not `Status.Ok`, the handle is not destroyed immediately and `_isInitialized` is never set to true so that also the `Dispose `method cannot destroy the handle. …

Memory leak in Tag.InitializeAsync in case of exceptions
